name: clusters-in-lang-eval
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - nltk
  - tqdm
  - matplotlib
  - seaborn
  - jupyterlab
  - pylint
  - pip
  - r-base
  - pip:
    - ipdb
    - rpy2
    - datasets
    - lxml
    - goose3
